import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

import '../core/design_tokens.dart';
import 'profile_onboarding_store.dart';
import 'providers/repositories.dart';
import '../presentation/providers/auth_providers.dart';
import '../presentation/providers/profile_providers.dart';

/// ログイン成功後: セッション確認 → プロフィール入力済みか判定 → 画面遷移。
class PostAuthFlow {
  PostAuthFlow._();

  static Future<bool> hasSession() async {
    // Native LINE/Apple auth establishes session via verifyOTP.
    // Avoid extra refresh here; it can be unstable depending on network/project.
    return Supabase.instance.client.auth.currentSession != null;
  }

  /// DB / メタデータ / 端末キャッシュから「初回プロフィール入力が不要か」を判定する。
  static Future<bool> isProfileSetupComplete(WidgetRef ref) async {
    final user = Supabase.instance.client.auth.currentUser;
    final userId = user?.id;
    if (userId == null || user == null) return false;

    // Do not block route decision on backend profile sync.
    // Post-login sync in main.dart also calls ensureBackendProfile.

    try {
      final profile = await ref
          .read(profileRepositoryProvider)
          .getProfile()
          .timeout(const Duration(seconds: 8));
      if (ProfileOnboardingStore.looksAutoGeneratedUsername(
        profile.username,
        userId,
      )) {
        await ProfileOnboardingStore.requireSetup(userId);
        return false;
      }
      if (ProfileOnboardingStore.isProfileFieldsComplete(
        username: profile.username,
        name: profile.name,
        userId: userId,
      )) {
        await ProfileOnboardingStore.setCompleted(userId);
        return true;
      }
      // レガシーアカウント: メタデータは完了でも username が不正な場合は再入力へ。
      await ProfileOnboardingStore.requireSetup(userId);
      return false;
    } catch (_) {}

    try {
      await ProfileOnboardingStore.applyPendingEmailSignup(
        userId: userId,
        email: user.email,
      ).timeout(const Duration(seconds: 3));
    } catch (_) {}

    return ProfileOnboardingStore.isCompleted(userId);
  }

  /// ログイン処理のあと: 認証画面を閉じて [AuthGate] の [_LoggedInShell] に任せる。
  /// プロフィール判定は [_LoggedInShell] で一度だけ行う（二重 API 呼び出しと黒画面を防ぐ）。
  ///
  /// [context] 配下の [ProviderScope] を使う（dispose 済み [WidgetRef] は使わない）。
  static Future<void> finishLogin({required BuildContext context}) async {
    if (kDebugMode) debugPrint('[PostAuthFlow] finishLogin:start');
    if (!await hasSession()) {
      if (kDebugMode) {
        debugPrint('[PostAuthFlow] finishLogin:no-session');
      }
      throw StateError('ログインに失敗しました。もう一度お試しください。');
    }
    if (kDebugMode) debugPrint('[PostAuthFlow] finishLogin:has-session');

    if (!context.mounted) return;

    final container = ProviderScope.containerOf(context);
    container.invalidate(authUserProvider);
    container.invalidate(profileControllerProvider);
    if (kDebugMode) debugPrint('[PostAuthFlow] finishLogin:providers-invalidated');

    if (!context.mounted) return;
    Navigator.of(context, rootNavigator: true).popUntil((route) => route.isFirst);
    if (kDebugMode) debugPrint('[PostAuthFlow] finishLogin:popUntil-reached');
  }

  static Future<T?> withLoading<T>(
    BuildContext context,
    Future<T> Function() action,
  ) async {
    if (!context.mounted) return null;
    final rootNav = Navigator.of(context, rootNavigator: true);
    showDialog<void>(
      context: context,
      barrierDismissible: false,
      barrierColor: AppColors.white.withValues(alpha: 0.92),
      builder: (_) => const Center(
        child: CircularProgressIndicator(color: AppColors.black),
      ),
    );
    try {
      return await action();
    } finally {
      if (rootNav.mounted && rootNav.canPop()) {
        rootNav.pop();
      }
    }
  }
}
