import 'package:shared_preferences/shared_preferences.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

const _kProfileSetupPrefix = 'panda_profile_setup_done_v1_';
const _kPendingEmailSignup = 'panda_pending_profile_setup_email_v1';
const _kAuthMetadataCompleteKey = 'profileSetupComplete';

/// ユーザーごとに初回プロフィール入力が済んだかを記録する。
/// 端末 [SharedPreferences] に加え、Auth メタデータと DB 上の username で復元する。
class ProfileOnboardingStore {
  static String _key(String userId) => '$_kProfileSetupPrefix$userId';

  static Future<bool> isCompleted(String userId) async {
    final prefs = await SharedPreferences.getInstance();
    if (prefs.getBool(_key(userId)) ?? false) return true;

    final user = Supabase.instance.client.auth.currentUser;
    if (user?.id != userId) return false;
    if (_metadataSaysComplete(user!.userMetadata)) {
      await setCompleted(userId);
      return true;
    }
    return false;
  }

  static Future<void> setCompleted(String userId) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_key(userId), true);
    await _markCompleteInAuthMetadata();
  }

  /// 新規登録直後は必ずプロフィール入力へ（メール確認後の初回ログイン含む）。
  static Future<void> requireSetup(String userId) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove(_key(userId));
  }

  /// メール確認待ちの新規登録（セッション未発行）用。
  static Future<void> markPendingEmailSignup(String email) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_kPendingEmailSignup, email.trim().toLowerCase());
  }

  /// 確認メールから初回ログインしたときだけ [requireSetup] を有効化する。
  /// 別アカウントのログイン時に残った pending は消す（毎回プロフィール入力になるのを防ぐ）。
  static Future<void> applyPendingEmailSignup({
    required String userId,
    String? email,
  }) async {
    final prefs = await SharedPreferences.getInstance();
    final pending = prefs.getString(_kPendingEmailSignup);
    if (pending == null) return;

    final normalizedEmail = email?.trim().toLowerCase();
    if (normalizedEmail == null || normalizedEmail != pending) {
      await prefs.remove(_kPendingEmailSignup);
      return;
    }

    await prefs.remove(_kPendingEmailSignup);
    if (await isCompleted(userId)) return;
    await requireSetup(userId);
  }

  static final _usernamePattern = RegExp(r'^[a-zA-Z0-9_]{3,30}$');

  /// 表示名・ユーザーコードが DB 上で埋まっているか（再ログイン時のスキップ用）。
  /// 自動採番 username でも値があればスキップする。
  static bool hasRequiredFieldsFilled({
    required String username,
    required String name,
  }) {
    final normalizedName = name.trim();
    final normalizedUsername = username.trim().toLowerCase();
    if (normalizedName.isEmpty ||
        normalizedName == '名無しさん' ||
        normalizedName == 'panda user') {
      return false;
    }
    if (normalizedUsername.isEmpty || normalizedUsername == 'unknown') {
      return false;
    }
    return _usernamePattern.hasMatch(normalizedUsername);
  }

  /// ユーザーが自分で決めた username か（厳しめ。同期用）。
  static bool isProfileFieldsComplete({
    required String username,
    required String name,
    required String userId,
  }) {
    if (!hasRequiredFieldsFilled(username: username, name: name)) {
      return false;
    }
    if (looksAutoGeneratedUsername(username, userId)) return false;
    return true;
  }

  /// [ensureBackendProfile] で自動採番された username かどうか。
  static bool looksAutoGeneratedUsername(String username, String userId) {
    final normalized = username.trim().toLowerCase();
    if (normalized.isEmpty || normalized == 'unknown') return true;
    final compactId = userId.replaceAll('-', '');
    if (compactId.length < 6) return false;
    final suffix = compactId.substring(0, 6).toLowerCase();
    return normalized.endsWith('_$suffix');
  }

  /// ユーザーがプロフィール設定で自分で決めた username なら完了扱いに同期する。
  static Future<bool> syncCompletedFromProfile({
    required String userId,
    required String username,
    String? name,
  }) async {
    if (!isProfileFieldsComplete(
      username: username,
      name: name ?? '',
      userId: userId,
    )) {
      return false;
    }
    await setCompleted(userId);
    return true;
  }

  static bool _metadataSaysComplete(Map<String, dynamic>? metadata) {
    final value = metadata?[_kAuthMetadataCompleteKey];
    return value == true || value == 'true';
  }

  static Future<void> _markCompleteInAuthMetadata() async {
    final user = Supabase.instance.client.auth.currentUser;
    if (user == null) return;
    if (_metadataSaysComplete(user.userMetadata)) return;
    try {
      await Supabase.instance.client.auth.updateUser(
        UserAttributes(data: {_kAuthMetadataCompleteKey: true}),
      );
    } catch (_) {
      // オフライン等でも prefs があれば次回まで問題ない
    }
  }
}
